import json

with open('Semi_Supervised_Graph_Pipeline.ipynb', 'r', encoding='utf-8') as f:
    nb = json.load(f)

# Fixing Cell 4 (Code for Target Variable - Index 8 in Notebook)
# Justifying and mapping the formula closer to exact RUSLE factors.
nb['cells'][8]['source'] = [
    "# Justification of RUSLE Formula:\n",
    "# We strictly align with the RUSLE components (A = R * K * LS * C * P).\n",
    "# 1. R-Factor ~ Rainfall (mm)\n",
    "# 2. K-Factor ~ Soil Cohesiveness (Mapped previously)\n",
    "# 3. LS-Factor Proxy ~ Based on Moore & Burch physical relationship with Slope: sin(slope)^1.3\n",
    "# 4. C-Factor Proxy ~ (Cover Management) mathematically derived from NDVI (Van Leeuwen, 2004)\n",
    "\n",
    "import numpy as np\n",
    "import matplotlib.pyplot as plt\n",
    "import seaborn as sns\n",
    "\n",
    "# Calculate C-Factor Proxy from NDVI. \n",
    "# High NDVI -> Heavy vegetation -> Low C-Factor (approx 0.01)\n",
    "# Negative NDVI (water/bare) -> High C-Factor (approx 1.0)\n",
    "df['c_factor_proxy'] = np.where(df['NDVI_Value'] > 0, np.exp(-2 * df['NDVI_Value'] / (1 - df['NDVI_Value'])), 1.0)\n",
    "\n",
    "# Calculate LS-Factor proxy using Sine of slope to approximate gravity pull\n",
    "df['ls_factor_proxy'] = np.power(np.sin(np.radians(df['Slope (Degree)'])), 1.3)\n",
    "\n",
    "# EXACT RELATIVE RUSLE SCORE (R * K * LS * C)\n",
    "df['Raw_Risk_Score'] = df['Rainfall (mm)'] * df['K_Factor'] * df['ls_factor_proxy'] * df['c_factor_proxy']\n",
    "\n",
    "# Identify 5th and 95th percentiles (The Extremes)\n",
    "p_05 = df['Raw_Risk_Score'].quantile(0.05)\n",
    "p_95 = df['Raw_Risk_Score'].quantile(0.95)\n",
    "\n",
    "# Generate the Semi-Supervised Mask (-1 = Unknown)\n",
    "def generate_label(row):\n",
    "    if row['Raw_Risk_Score'] >= p_95:\n",
    "        return 1  # High Risk (Top 5%)\n",
    "    elif row['Raw_Risk_Score'] <= p_05:\n",
    "        return 0  # Low Risk (Bottom 5%)\n",
    "    else:\n",
    "        return -1 # Unknown (Middle 90%)\n",
    "\n",
    "df['Target_Label'] = df.apply(generate_label, axis=1)\n",
    "\n",
    "print(f'Top 5% Risk Threshold: {p_95:.5f}')\n",
    "print(f'Bottom 5% Safe Threshold: {p_05:.5f}')\n",
    "print('Label Distribution:')\n",
    "print(df['Target_Label'].value_counts())\n",
    "\n",
    "plt.figure(figsize=(6,4))\n",
    "sns.countplot(x='Target_Label', data=df, palette='coolwarm')\n",
    "plt.title('Semi-Supervised Labels (-1=Unknown, 0=Safe, 1=Severe)')\n",
    "plt.show()\n"
]

# Fixing Cell 5 (Continuous Feature Engineering - Index 10 in Notebook)
# Added Categorical Encoding + NaN filling to prevent Loss: NaN
nb['cells'][10]['source'] = [
    "# CIRUCLAR ASPECT\n",
    "df['Aspect_Sin'] = np.sin(np.radians(df['Aspect (Degree)']))\n",
    "df['Aspect_Cos'] = np.cos(np.radians(df['Aspect (Degree)']))\n",
    "\n",
    "# CRITICAL BUG FIX: FILL NULLS IN CONTINUOUS FEATURES BEFORE SCALING\n",
    "# If any column has a NaN, StandardScaler generates NaNs everywhere, crashing the PyTorch Loss function!\n",
    "features_to_scale = ['Elevation (m)', 'Slope (Degree)', 'Rainfall (mm)', 'NDVI_Value', 'TWI', 'SPI', 'TRI', 'Plan Curvature', 'Profile Curvature', 'Drainage Density (m)']\n",
    "df[features_to_scale] = df[features_to_scale].fillna(df[features_to_scale].median())\n",
    "\n",
    "# Standard Scaling\n",
    "from sklearn.preprocessing import StandardScaler\n",
    "scaler = StandardScaler()\n",
    "df[features_to_scale] = scaler.fit_transform(df[features_to_scale])\n",
    "\n",
    "# CATEGORICAL ENGINEERING (One-Hot Encoding)\n",
    "df['Geology_Formation'] = df['Geology_Formation'].fillna('Unknown_Geo')\n",
    "df['Land_Use'] = df['Land_Use'].fillna('Unknown_LU')\n",
    "cat_encoded = pd.get_dummies(df[['Geology_Formation', 'Land_Use']], drop_first=True)\n",
    "# We save the generated column names to dynamically add them to the Neural Network!\n",
    "cat_columns = cat_encoded.columns.tolist()\n",
    "df = pd.concat([df, cat_encoded], axis=1)\n",
    "\n",
    "print('Features Engineered and Scaled! Nulls removed. Categoricals One-Hot Encoded.')\n",
    "display(df[['Aspect_Sin', 'TWI'] + cat_columns[:2]].head(3))\n"
]

# Fixing PyG Data (Index 14) to include one-hot encoded 'cat_columns'
nb['cells'][14]['source'] = [
    "from torch_geometric.data import Data\n",
    "import torch\n",
    "\n",
    "# 1. Feature Matrix (x) -> NOW INCLUDES CATEGORICAL ONE-HOT COLUMNS\n",
    "base_features = ['K_Factor', 'Elevation (m)', 'Slope (Degree)', 'Rainfall (mm)', \n",
    "                 'NDVI_Value', 'TWI', 'SPI', 'TRI', 'Plan Curvature', 'Profile Curvature', \n",
    "                 'Aspect_Sin', 'Aspect_Cos', 'Drainage Density (m)']\n",
    "\n",
    "# Combine continuous features with the newly one-hot encoded categoricals\n",
    "all_features = base_features + cat_columns\n",
    "\n",
    "# Fill any lingering NaNs to be absolutely sure the loss won't crash\n",
    "x_raw = df[all_features].fillna(0).values\n",
    "x = torch.tensor(x_raw.astype('float32'), dtype=torch.float)\n",
    "\n",
    "# 2. Target Variable (y)\n",
    "y = torch.tensor(df['Target_Label'].values, dtype=torch.long)\n",
    "\n",
    "# 3. Training Mask (Only learn from labels 0 and 1, ignore -1)\n",
    "train_mask = (y != -1)\n",
    "\n",
    "# 4. PyG Data Object\n",
    "graph_data = Data(x=x, edge_index=edge_index, y=y)\n",
    "graph_data.train_mask = train_mask\n",
    "\n",
    "print('PyTorch Geometric Data Object created:')\n",
    "print(graph_data)\n",
    "print(f'Training on {train_mask.sum().item()} known nodes out of {len(y)} total.')\n",
    "print(f'Total input features for the network: {x.shape[1]}')\n"
]

# Fixing Training Loop early stopping (Index 18)
nb['cells'][18]['source'] = [
    "optimizer = torch.optim.Adam(model.parameters(), lr=0.01, weight_decay=5e-4)\n",
    "criterion = torch.nn.NLLLoss()\n",
    "\n",
    "def train():\n",
    "    model.train()\n",
    "    optimizer.zero_grad()\n",
    "    out = model(graph_data.x, graph_data.edge_index)\n",
    "    loss = criterion(out[graph_data.train_mask], graph_data.y[graph_data.train_mask])\n",
    "    loss.backward()\n",
    "    optimizer.step()\n",
    "    return loss.item()\n",
    "\n",
    "print('Starting Training Loop with Early Stopping...')\n",
    "best_loss = float('inf')\n",
    "loss_change = float('inf')\n",
    "\n",
    "for epoch in range(1, 401):  # Can go longer because early stopping will catch it\n",
    "    loss = train()\n",
    "    \n",
    "    if epoch > 1:\n",
    "        loss_change = abs(best_loss - loss)\n",
    "        \n",
    "    if loss < best_loss:\n",
    "        best_loss = loss\n",
    "        \n",
    "    if epoch % 10 == 0:\n",
    "        print(f'Epoch: {epoch:03d}, Loss: {loss:.4f}, Delta: {loss_change:.5f}')\n",
    "        \n",
    "    # EARLY STOPPING logic requested by user\n",
    "    if epoch > 50 and loss_change < 0.005:\n",
    "        print(f'\\nEarly stopping triggered at epoch {epoch}! Marginal loss change ({loss_change:.5f}) is < 0.005.')\n",
    "        break\n",
    "\n",
    "print('Training Complete!')\n"
]

with open('Semi_Supervised_Graph_Pipeline.ipynb', 'w', encoding='utf-8') as f:
    json.dump(nb, f, indent=2)

print("Notebook successfully updated with RUSLE justifications, NaN fixes, Categorical Encodings, and Early Stopping!")
